### ISSUE TITLE
symantec scanner

### ISSUE THREAD

**Issue by carlkl** [liuyug/meditor#1]
meditor-0.2.7.2.exe hits at virsutotal.com: MalwarePatrol
And on my local system meditor.exe is rejected due to heuristics scan of symantec protection.

**Comment by liuyug** [comment]
It don't raise virus warning in my Windows 10 with defender.

I advise remove the file and download latest version 2.7.4. I will attach its MD5.

**Comment by carlkl** [comment]
I'm sure, that this problem is due to the symantec scanner itself. With the new release the problem remains: `Heur.AdvML.B`
I will sent an report to symantec

**Comment by carlkl** [comment]
No idea why, but this error is gone now. Maybe my complaint to Symantec helped.
